// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const addAlertService = `-- name: AddAlertService :exec
insert into alert_service(alert_id, service_id) values(?, ?)
`

type AddAlertServiceParams struct {
	AlertID   int64
	ServiceID int64
}

func (q *Queries) AddAlertService(ctx context.Context, arg AddAlertServiceParams) error {
	_, err := q.db.ExecContext(ctx, addAlertService, arg.AlertID, arg.ServiceID)
	return err
}

const checkHasRecentPendingEmailAlertSubscription = `-- name: CheckHasRecentPendingEmailAlertSubscription :one
select exists(
    select 1 from pending_email_alert_subscription where email = ?
    and created_at > datetime(?, '-10 minutes')
)
`

type CheckHasRecentPendingEmailAlertSubscriptionParams struct {
	Email    string
	Datetime interface{}
}

func (q *Queries) CheckHasRecentPendingEmailAlertSubscription(ctx context.Context, arg CheckHasRecentPendingEmailAlertSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkHasRecentPendingEmailAlertSubscription, arg.Email, arg.Datetime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAlert = `-- name: CreateAlert :one
insert into alert(title, type, severity, created_at) values(?, ?, ?, ?) returning id
`

type CreateAlertParams struct {
	Title     string
	Type      string
	Severity  string
	CreatedAt time.Time
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.Title,
		arg.Type,
		arg.Severity,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAlertMessage = `-- name: CreateAlertMessage :one
insert into alert_message(content, created_at, alert_id) values(?, ?, ?) returning id
`

type CreateAlertMessageParams struct {
	Content   string
	CreatedAt time.Time
	AlertID   int64
}

func (q *Queries) CreateAlertMessage(ctx context.Context, arg CreateAlertMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAlertMessage, arg.Content, arg.CreatedAt, arg.AlertID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAlertMessageNotifications = `-- name: CreateAlertMessageNotifications :exec
insert into alert_notification(created_at, alert_subscription_id, alert_message_id)
select ?, id, ? from alert_subscription where alert_subscription.active = true
`

type CreateAlertMessageNotificationsParams struct {
	CreatedAt      time.Time
	AlertMessageID int64
}

func (q *Queries) CreateAlertMessageNotifications(ctx context.Context, arg CreateAlertMessageNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, createAlertMessageNotifications, arg.CreatedAt, arg.AlertMessageID)
	return err
}

const createAlertSMTPNotificationSetting = `-- name: CreateAlertSMTPNotificationSetting :exec
insert into alert_setting_smtp_notification(notification_channel_id) values(?)
`

func (q *Queries) CreateAlertSMTPNotificationSetting(ctx context.Context, notificationChannelID int64) error {
	_, err := q.db.ExecContext(ctx, createAlertSMTPNotificationSetting, notificationChannelID)
	return err
}

const createAlertSubscription = `-- name: CreateAlertSubscription :exec
insert into alert_subscription(type, destination, meta) values(?, ?, nullif(?, ''))
on conflict(type, destination) do update set active = true
`

type CreateAlertSubscriptionParams struct {
	Type        string
	Destination string
	NULLIF      interface{}
}

func (q *Queries) CreateAlertSubscription(ctx context.Context, arg CreateAlertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createAlertSubscription, arg.Type, arg.Destination, arg.NULLIF)
	return err
}

const createPendingEmailAlertSubscription = `-- name: CreatePendingEmailAlertSubscription :exec
insert into pending_email_alert_subscription(token, email, created_at)
values(?, ?, ?)
`

type CreatePendingEmailAlertSubscriptionParams struct {
	Token     string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreatePendingEmailAlertSubscription(ctx context.Context, arg CreatePendingEmailAlertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createPendingEmailAlertSubscription, arg.Token, arg.Email, arg.CreatedAt)
	return err
}

const deleteAlertByID = `-- name: DeleteAlertByID :exec
delete from alert where id = ?
`

func (q *Queries) DeleteAlertByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertByID, id)
	return err
}

const deleteAlertMessageByID = `-- name: DeleteAlertMessageByID :exec
delete from alert_message where alert_id = ? and id = ?
`

type DeleteAlertMessageByIDParams struct {
	AlertID int64
	ID      int64
}

func (q *Queries) DeleteAlertMessageByID(ctx context.Context, arg DeleteAlertMessageByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlertMessageByID, arg.AlertID, arg.ID)
	return err
}

const deleteAlertSMTPNotificationSetting = `-- name: DeleteAlertSMTPNotificationSetting :exec
delete from alert_setting_smtp_notification
`

func (q *Queries) DeleteAlertSMTPNotificationSetting(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAlertSMTPNotificationSetting)
	return err
}

const deleteAlertServicesByAlertID = `-- name: DeleteAlertServicesByAlertID :exec
delete from alert_service where alert_id = ?
`

func (q *Queries) DeleteAlertServicesByAlertID(ctx context.Context, alertID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertServicesByAlertID, alertID)
	return err
}

const deleteAlertSubscriptionByMeta = `-- name: DeleteAlertSubscriptionByMeta :exec
delete from alert_subscription where meta = ?
`

func (q *Queries) DeleteAlertSubscriptionByMeta(ctx context.Context, meta sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteAlertSubscriptionByMeta, meta)
	return err
}

const editAlert = `-- name: EditAlert :exec
update alert set title = ?, type = ?, severity = ? where id = ?
`

type EditAlertParams struct {
	Title    string
	Type     string
	Severity string
	ID       int64
}

func (q *Queries) EditAlert(ctx context.Context, arg EditAlertParams) error {
	_, err := q.db.ExecContext(ctx, editAlert,
		arg.Title,
		arg.Type,
		arg.Severity,
		arg.ID,
	)
	return err
}

const editAlertMessage = `-- name: EditAlertMessage :exec
update alert_message set content = ?, last_updated_at = ?
where alert_id = ? and id = ?
`

type EditAlertMessageParams struct {
	Content       string
	LastUpdatedAt sql.NullTime
	AlertID       int64
	ID            int64
}

func (q *Queries) EditAlertMessage(ctx context.Context, arg EditAlertMessageParams) error {
	_, err := q.db.ExecContext(ctx, editAlertMessage,
		arg.Content,
		arg.LastUpdatedAt,
		arg.AlertID,
		arg.ID,
	)
	return err
}

const getAlertByID = `-- name: GetAlertByID :one
select id, title, type, severity, created_at, ended_at from alert where id = ?
`

func (q *Queries) GetAlertByID(ctx context.Context, id int64) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Severity,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getAlertSMTPNotificationSetting = `-- name: GetAlertSMTPNotificationSetting :one
select notification_channel_id from alert_setting_smtp_notification limit 1
`

func (q *Queries) GetAlertSMTPNotificationSetting(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAlertSMTPNotificationSetting)
	var notification_channel_id int64
	err := row.Scan(&notification_channel_id)
	return notification_channel_id, err
}

const getAlertSubscriptionByEmail = `-- name: GetAlertSubscriptionByEmail :one
select id, type, destination, meta, active from alert_subscription
where type = 'email' and destination = ?
`

func (q *Queries) GetAlertSubscriptionByEmail(ctx context.Context, destination string) (AlertSubscription, error) {
	row := q.db.QueryRowContext(ctx, getAlertSubscriptionByEmail, destination)
	var i AlertSubscription
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Destination,
		&i.Meta,
		&i.Active,
	)
	return i, err
}

const getOldestAlertDate = `-- name: GetOldestAlertDate :one
select created_at from alert order by created_at asc limit 1
`

func (q *Queries) GetOldestAlertDate(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getOldestAlertDate)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getPendingEmailAlertSubscriptionEmailByToken = `-- name: GetPendingEmailAlertSubscriptionEmailByToken :one
select email from pending_email_alert_subscription
where token = ? and confirmed_at is null and created_at > ?
`

type GetPendingEmailAlertSubscriptionEmailByTokenParams struct {
	Token     string
	CreatedAt time.Time
}

func (q *Queries) GetPendingEmailAlertSubscriptionEmailByToken(ctx context.Context, arg GetPendingEmailAlertSubscriptionEmailByTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPendingEmailAlertSubscriptionEmailByToken, arg.Token, arg.CreatedAt)
	var email string
	err := row.Scan(&email)
	return email, err
}

const listActiveAlertEmailSubscriptions = `-- name: ListActiveAlertEmailSubscriptions :many
select id, type, destination, meta, active from alert_subscription
where type = 'email' and active = true
`

func (q *Queries) ListActiveAlertEmailSubscriptions(ctx context.Context) ([]AlertSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlertEmailSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertSubscription{}
	for rows.Next() {
		var i AlertSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Destination,
			&i.Meta,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertMessagesByAlertID = `-- name: ListAlertMessagesByAlertID :many
select id, content, created_at, last_updated_at, alert_id
from alert_message
where alert_id = ?
order by created_at desc
`

func (q *Queries) ListAlertMessagesByAlertID(ctx context.Context, alertID int64) ([]AlertMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAlertMessagesByAlertID, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertMessage{}
	for rows.Next() {
		var i AlertMessage
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertMessagesInPeriod = `-- name: ListAlertMessagesInPeriod :many
select id, content, created_at, last_updated_at, alert_id
from alert_message
where alert_id in (select id from alert where alert.created_at >= ? and alert.created_at < ?)
order by created_at desc
`

type ListAlertMessagesInPeriodParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) ListAlertMessagesInPeriod(ctx context.Context, arg ListAlertMessagesInPeriodParams) ([]AlertMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAlertMessagesInPeriod, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertMessage{}
	for rows.Next() {
		var i AlertMessage
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertServicesByAlertID = `-- name: ListAlertServicesByAlertID :many
select service.id, service.name, service.helper_text, alert_id
from alert_service
left join service on service.id = alert_service.service_id
where alert_id = ?
`

type ListAlertServicesByAlertIDRow struct {
	ID         sql.NullInt64
	Name       sql.NullString
	HelperText sql.NullString
	AlertID    int64
}

func (q *Queries) ListAlertServicesByAlertID(ctx context.Context, alertID int64) ([]ListAlertServicesByAlertIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertServicesByAlertID, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertServicesByAlertIDRow{}
	for rows.Next() {
		var i ListAlertServicesByAlertIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HelperText,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertServicesInPeriod = `-- name: ListAlertServicesInPeriod :many
select service.id, service.name, service.helper_text, alert_id
from alert_service
left join service on service.id = alert_service.service_id
where alert_id in (select id from alert where alert.created_at >= ? and alert.created_at < ?)
`

type ListAlertServicesInPeriodParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type ListAlertServicesInPeriodRow struct {
	ID         sql.NullInt64
	Name       sql.NullString
	HelperText sql.NullString
	AlertID    int64
}

func (q *Queries) ListAlertServicesInPeriod(ctx context.Context, arg ListAlertServicesInPeriodParams) ([]ListAlertServicesInPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertServicesInPeriod, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertServicesInPeriodRow{}
	for rows.Next() {
		var i ListAlertServicesInPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HelperText,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertSettings = `-- name: ListAlertSettings :many
select name, value from alert_setting
`

type ListAlertSettingsRow struct {
	Name  string
	Value string
}

func (q *Queries) ListAlertSettings(ctx context.Context) ([]ListAlertSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertSettingsRow{}
	for rows.Next() {
		var i ListAlertSettingsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
select id, title, type, severity, created_at, ended_at from alert
order by created_at desc
`

func (q *Queries) ListAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Severity,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsInPeriod = `-- name: ListAlertsInPeriod :many
select id, title, type, severity, created_at, ended_at
from alert
where created_at >= ? and created_at < ?
order by created_at desc
`

type ListAlertsInPeriodParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) ListAlertsInPeriod(ctx context.Context, arg ListAlertsInPeriodParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsInPeriod, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Severity,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingAlertMessages = `-- name: ListOngoingAlertMessages :many

select id, content, created_at, last_updated_at, alert_id
from alert_message
where alert_id in (select id from alert where ended_at is null)
order by created_at desc
`

// sqlc's sqlite engine has no dynamic IN list, so each view re-expresses its
// alert set as a subquery instead of interpolating the ids just fetched.
func (q *Queries) ListOngoingAlertMessages(ctx context.Context) ([]AlertMessage, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingAlertMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertMessage{}
	for rows.Next() {
		var i AlertMessage
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingAlertServices = `-- name: ListOngoingAlertServices :many
select service.id, service.name, service.helper_text, alert_id
from alert_service
left join service on service.id = alert_service.service_id
where alert_id in (select id from alert where ended_at is null)
`

type ListOngoingAlertServicesRow struct {
	ID         sql.NullInt64
	Name       sql.NullString
	HelperText sql.NullString
	AlertID    int64
}

func (q *Queries) ListOngoingAlertServices(ctx context.Context) ([]ListOngoingAlertServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingAlertServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOngoingAlertServicesRow{}
	for rows.Next() {
		var i ListOngoingAlertServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HelperText,
			&i.AlertID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOngoingAlerts = `-- name: ListOngoingAlerts :many
select id, title, type, severity, created_at, ended_at
from alert
where ended_at is null
order by case
    when severity = 'red' then 1
    when severity = 'amber' then 2
    else 3
end asc
`

func (q *Queries) ListOngoingAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listOngoingAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Severity,
			&i.CreatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsentAlertNotifications = `-- name: ListUnsentAlertNotifications :many
select
    alert_notification.id, alert_subscription.destination, alert_message.content,
    alert_subscription.type, alert_message.id as alert_message_id, alert.title,
    alert.type as alert_type, alert.severity,
    -- char(8226) is the bullet separator, spelled out because a literal
    -- multi-byte character here shifts sqlc's offsets and silently truncates
    -- every query after it in the file.
    -- coalesce because deleting the last service an alert names cascades its
    -- alert_service rows away, and group_concat over no rows is null.
    cast(
        coalesce(group_concat(service.name, ' ' || char(8226) || ' '), '') as text
    ) as alert_services
from alert_notification
left join alert_subscription on alert_subscription.id = alert_subscription_id
left join alert_message on alert_message.id = alert_message_id
left join alert on alert.id = alert_message.alert_id
left join alert_service on alert_service.alert_id = alert_message.alert_id
left join service on service.id = alert_service.service_id
where alert_notification.sent_at is null
group by alert_notification.id
order by alert_message.created_at asc
`

type ListUnsentAlertNotificationsRow struct {
	ID             int64
	Destination    sql.NullString
	Content        sql.NullString
	Type           sql.NullString
	AlertMessageID sql.NullInt64
	Title          sql.NullString
	AlertType      sql.NullString
	Severity       sql.NullString
	AlertServices  string
}

func (q *Queries) ListUnsentAlertNotifications(ctx context.Context) ([]ListUnsentAlertNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnsentAlertNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsentAlertNotificationsRow{}
	for rows.Next() {
		var i ListUnsentAlertNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Destination,
			&i.Content,
			&i.Type,
			&i.AlertMessageID,
			&i.Title,
			&i.AlertType,
			&i.Severity,
			&i.AlertServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAlertNotifications = `-- name: PruneAlertNotifications :execrows
delete from alert_notification where id in (
    select id from alert_notification
    where alert_notification.sent_at is not null and alert_notification.sent_at < ? limit ?
)
`

type PruneAlertNotificationsParams struct {
	SentAt sql.NullTime
	Limit  int64
}

func (q *Queries) PruneAlertNotifications(ctx context.Context, arg PruneAlertNotificationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAlertNotifications, arg.SentAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const prunePendingEmailAlertSubscriptions = `-- name: PrunePendingEmailAlertSubscriptions :execrows
delete from pending_email_alert_subscription where id in (
    select id from pending_email_alert_subscription
    where pending_email_alert_subscription.created_at < ? limit ?
)
`

type PrunePendingEmailAlertSubscriptionsParams struct {
	CreatedAt time.Time
	Limit     int64
}

func (q *Queries) PrunePendingEmailAlertSubscriptions(ctx context.Context, arg PrunePendingEmailAlertSubscriptionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, prunePendingEmailAlertSubscriptions, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveAlert = `-- name: ResolveAlert :exec
update alert set ended_at = ? where id = ?
`

type ResolveAlertParams struct {
	EndedAt sql.NullTime
	ID      int64
}

func (q *Queries) ResolveAlert(ctx context.Context, arg ResolveAlertParams) error {
	_, err := q.db.ExecContext(ctx, resolveAlert, arg.EndedAt, arg.ID)
	return err
}

const unresolveAlert = `-- name: UnresolveAlert :exec
update alert set ended_at = null where id = ?
`

func (q *Queries) UnresolveAlert(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unresolveAlert, id)
	return err
}

const updateAlertSentAtByID = `-- name: UpdateAlertSentAtByID :exec
update alert_notification set sent_at = ? where id = ?
`

type UpdateAlertSentAtByIDParams struct {
	SentAt sql.NullTime
	ID     int64
}

func (q *Queries) UpdateAlertSentAtByID(ctx context.Context, arg UpdateAlertSentAtByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertSentAtByID, arg.SentAt, arg.ID)
	return err
}

const updateEmailAlertSubscriptionActiveByEmail = `-- name: UpdateEmailAlertSubscriptionActiveByEmail :exec
update alert_subscription set active = ? where destination = ? and type = 'email'
`

type UpdateEmailAlertSubscriptionActiveByEmailParams struct {
	Active      int64
	Destination string
}

func (q *Queries) UpdateEmailAlertSubscriptionActiveByEmail(ctx context.Context, arg UpdateEmailAlertSubscriptionActiveByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailAlertSubscriptionActiveByEmail, arg.Active, arg.Destination)
	return err
}

const updateEmailAlertSubscriptionActiveByMeta = `-- name: UpdateEmailAlertSubscriptionActiveByMeta :exec
update alert_subscription set active = ? where meta = ? and type = 'email'
`

type UpdateEmailAlertSubscriptionActiveByMetaParams struct {
	Active int64
	Meta   sql.NullString
}

func (q *Queries) UpdateEmailAlertSubscriptionActiveByMeta(ctx context.Context, arg UpdateEmailAlertSubscriptionActiveByMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailAlertSubscriptionActiveByMeta, arg.Active, arg.Meta)
	return err
}

const updatePendingEmailAlertSubscription = `-- name: UpdatePendingEmailAlertSubscription :exec
update pending_email_alert_subscription set confirmed_at = ? where token = ?
`

type UpdatePendingEmailAlertSubscriptionParams struct {
	ConfirmedAt sql.NullTime
	Token       string
}

func (q *Queries) UpdatePendingEmailAlertSubscription(ctx context.Context, arg UpdatePendingEmailAlertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updatePendingEmailAlertSubscription, arg.ConfirmedAt, arg.Token)
	return err
}

const upsertAlertSetting = `-- name: UpsertAlertSetting :exec
insert into alert_setting(name, value) values(?, ?)
on conflict(name) do update set value = excluded.value
`

type UpsertAlertSettingParams struct {
	Name  string
	Value string
}

func (q *Queries) UpsertAlertSetting(ctx context.Context, arg UpsertAlertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlertSetting, arg.Name, arg.Value)
	return err
}
