// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package sqlcgen

import (
	"context"
)

const getMetaValue = `-- name: GetMetaValue :one
select value from meta where name = ?
`

func (q *Queries) GetMetaValue(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetaValue, name)
	var value string
	err := row.Scan(&value)
	return value, err
}

const updateMetaValue = `-- name: UpdateMetaValue :exec
insert into meta(name, value) values(?, ?)
on conflict(name) do update set value = excluded.value
`

type UpdateMetaValueParams struct {
	Name  string
	Value string
}

func (q *Queries) UpdateMetaValue(ctx context.Context, arg UpdateMetaValueParams) error {
	_, err := q.db.ExecContext(ctx, updateMetaValue, arg.Name, arg.Value)
	return err
}
