// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Alert struct {
	ID        int64
	Title     string
	Type      string
	Severity  string
	CreatedAt time.Time
	EndedAt   sql.NullTime
}

type AlertMessage struct {
	ID            int64
	Content       string
	CreatedAt     time.Time
	LastUpdatedAt sql.NullTime
	AlertID       int64
}

type AlertNotification struct {
	ID                  int64
	CreatedAt           time.Time
	SentAt              sql.NullTime
	AlertSubscriptionID int64
	AlertMessageID      int64
}

type AlertService struct {
	ID        int64
	AlertID   int64
	ServiceID int64
}

type AlertSetting struct {
	ID    int64
	Name  string
	Value string
}

type AlertSettingSmtpNotification struct {
	ID                    int64
	NotificationChannelID int64
}

type AlertSubscription struct {
	ID          int64
	Type        string
	Destination string
	Meta        sql.NullString
	Active      int64
}

type MailGroup struct {
	ID          int64
	Slug        string
	Name        string
	Description sql.NullString
}

type MailGroupMember struct {
	ID           int64
	EmailAddress string
	MailGroupID  int64
}

type MailGroupMonitor struct {
	ID          int64
	MailGroupID int64
	MonitorID   int64
}

type Meta struct {
	ID    int64
	Name  string
	Value string
}

type Migration struct {
	ID      int64
	Name    string
	Skipped int64
}

type Monitor struct {
	ID             int64
	Slug           string
	Name           string
	Url            string
	Method         string
	Frequency      int64
	Timeout        int64
	Attempts       int64
	RequestHeaders sql.NullString
	BodyFormat     sql.NullString
	Body           sql.NullString
}

type MonitorLog struct {
	ID           int64
	StartedAt    time.Time
	EndedAt      time.Time
	ResponseCode sql.NullInt64
	ErrorMessage sql.NullString
	Attempts     int64
	Result       string
	MonitorID    int64
}

type MonitorLogLastChecked struct {
	ID           int64
	CheckedAt    time.Time
	MonitorID    interface{}
	MonitorLogID int64
}

type MonitorNotificationChannel struct {
	ID                    int64
	MonitorID             int64
	NotificationChannelID int64
}

type NotificationChannel struct {
	ID      int64
	Slug    string
	Name    string
	Type    string
	Details string
}

type PendingEmailAlertSubscription struct {
	ID          int64
	Token       string
	Email       string
	CreatedAt   time.Time
	ConfirmedAt sql.NullTime
}

type Service struct {
	ID         int64
	Slug       string
	Name       string
	HelperText string
}

type Session struct {
	ID        int64
	Token     string
	CsrfToken string
	CreatedAt time.Time
	UserID    int64
}

type Severity struct {
	Severity string
}

type User struct {
	ID       int64
	Username string
	Password string
}

type UserInvitation struct {
	ID        int64
	Token     string
	CreatedAt time.Time
}
