// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createMailGroupMonitor = `-- name: CreateMailGroupMonitor :exec
insert into mail_group_monitor(monitor_id, mail_group_id) values(?, ?)
`

type CreateMailGroupMonitorParams struct {
	MonitorID   int64
	MailGroupID int64
}

func (q *Queries) CreateMailGroupMonitor(ctx context.Context, arg CreateMailGroupMonitorParams) error {
	_, err := q.db.ExecContext(ctx, createMailGroupMonitor, arg.MonitorID, arg.MailGroupID)
	return err
}

const createMonitor = `-- name: CreateMonitor :one
insert into monitor(
    slug, name, url, method, frequency, timeout, attempts,
    request_headers, body_format, body
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning id
`

type CreateMonitorParams struct {
	Slug           string
	Name           string
	Url            string
	Method         string
	Frequency      int64
	Timeout        int64
	Attempts       int64
	RequestHeaders sql.NullString
	BodyFormat     sql.NullString
	Body           sql.NullString
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMonitor,
		arg.Slug,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Frequency,
		arg.Timeout,
		arg.Attempts,
		arg.RequestHeaders,
		arg.BodyFormat,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMonitorLog = `-- name: CreateMonitorLog :one
insert into monitor_log(
    started_at, ended_at, response_code, error_message, attempts, result, monitor_id
) values(?, ?, ?, ?, ?, ?, ?) returning id
`

type CreateMonitorLogParams struct {
	StartedAt    time.Time
	EndedAt      time.Time
	ResponseCode sql.NullInt64
	ErrorMessage sql.NullString
	Attempts     int64
	Result       string
	MonitorID    int64
}

func (q *Queries) CreateMonitorLog(ctx context.Context, arg CreateMonitorLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMonitorLog,
		arg.StartedAt,
		arg.EndedAt,
		arg.ResponseCode,
		arg.ErrorMessage,
		arg.Attempts,
		arg.Result,
		arg.MonitorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMonitorLogLastChecked = `-- name: CreateMonitorLogLastChecked :exec
insert into monitor_log_last_checked(checked_at, monitor_id, monitor_log_id)
values(?, ?, ?)
on conflict(monitor_id) do update set
    checked_at = excluded.checked_at,
    monitor_log_id = excluded.monitor_log_id
`

type CreateMonitorLogLastCheckedParams struct {
	CheckedAt    time.Time
	MonitorID    interface{}
	MonitorLogID int64
}

func (q *Queries) CreateMonitorLogLastChecked(ctx context.Context, arg CreateMonitorLogLastCheckedParams) error {
	_, err := q.db.ExecContext(ctx, createMonitorLogLastChecked, arg.CheckedAt, arg.MonitorID, arg.MonitorLogID)
	return err
}

const createMonitorNotificationChannel = `-- name: CreateMonitorNotificationChannel :exec
insert into monitor_notification_channel(monitor_id, notification_channel_id)
values(?, ?)
`

type CreateMonitorNotificationChannelParams struct {
	MonitorID             int64
	NotificationChannelID int64
}

func (q *Queries) CreateMonitorNotificationChannel(ctx context.Context, arg CreateMonitorNotificationChannelParams) error {
	_, err := q.db.ExecContext(ctx, createMonitorNotificationChannel, arg.MonitorID, arg.NotificationChannelID)
	return err
}

const deleteMailGroupMonitors = `-- name: DeleteMailGroupMonitors :exec
delete from mail_group_monitor where monitor_id = ?
`

func (q *Queries) DeleteMailGroupMonitors(ctx context.Context, monitorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMailGroupMonitors, monitorID)
	return err
}

const deleteMonitorByID = `-- name: DeleteMonitorByID :exec
delete from monitor where id = ?
`

func (q *Queries) DeleteMonitorByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitorByID, id)
	return err
}

const deleteMonitorNotificationChannels = `-- name: DeleteMonitorNotificationChannels :exec
delete from monitor_notification_channel where monitor_id = ?
`

func (q *Queries) DeleteMonitorNotificationChannels(ctx context.Context, monitorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMonitorNotificationChannels, monitorID)
	return err
}

const editMonitor = `-- name: EditMonitor :exec
update monitor set
    name = ?, url = ?, method = ?, frequency = ?, timeout = ?, attempts = ?,
    request_headers = ?, body_format = ?, body = ?
where
    id = ?
`

type EditMonitorParams struct {
	Name           string
	Url            string
	Method         string
	Frequency      int64
	Timeout        int64
	Attempts       int64
	RequestHeaders sql.NullString
	BodyFormat     sql.NullString
	Body           sql.NullString
	ID             int64
}

func (q *Queries) EditMonitor(ctx context.Context, arg EditMonitorParams) error {
	_, err := q.db.ExecContext(ctx, editMonitor,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Frequency,
		arg.Timeout,
		arg.Attempts,
		arg.RequestHeaders,
		arg.BodyFormat,
		arg.Body,
		arg.ID,
	)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
select
    id, name, url, method, frequency, timeout, attempts,
    request_headers, body_format, body
from
    monitor
where
    id = ?
`

type GetMonitorByIDRow struct {
	ID             int64
	Name           string
	Url            string
	Method         string
	Frequency      int64
	Timeout        int64
	Attempts       int64
	RequestHeaders sql.NullString
	BodyFormat     sql.NullString
	Body           sql.NullString
}

func (q *Queries) GetMonitorByID(ctx context.Context, id int64) (GetMonitorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMonitorByID, id)
	var i GetMonitorByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Frequency,
		&i.Timeout,
		&i.Attempts,
		&i.RequestHeaders,
		&i.BodyFormat,
		&i.Body,
	)
	return i, err
}

const getMonitorLogLastChecked = `-- name: GetMonitorLogLastChecked :one
select
    monitor_log.monitor_id, checked_at, monitor_log.response_code
from
    monitor_log_last_checked
    left join monitor_log on monitor_log.id = monitor_log_last_checked.monitor_log_id
where
    monitor_log_last_checked.monitor_id = ?
`

type GetMonitorLogLastCheckedRow struct {
	MonitorID    sql.NullInt64
	CheckedAt    time.Time
	ResponseCode sql.NullInt64
}

func (q *Queries) GetMonitorLogLastChecked(ctx context.Context, monitorID interface{}) (GetMonitorLogLastCheckedRow, error) {
	row := q.db.QueryRowContext(ctx, getMonitorLogLastChecked, monitorID)
	var i GetMonitorLogLastCheckedRow
	err := row.Scan(&i.MonitorID, &i.CheckedAt, &i.ResponseCode)
	return i, err
}

const getSeverity = `-- name: GetSeverity :one
select severity from severity limit 1
`

func (q *Queries) GetSeverity(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSeverity)
	var severity string
	err := row.Scan(&severity)
	return severity, err
}

const listAllMonitorLogLastChecked = `-- name: ListAllMonitorLogLastChecked :many
select
    monitor_log.monitor_id, checked_at, monitor_log.response_code
from
    monitor_log_last_checked
    left join monitor_log on monitor_log.id = monitor_log_last_checked.monitor_log_id
`

type ListAllMonitorLogLastCheckedRow struct {
	MonitorID    sql.NullInt64
	CheckedAt    time.Time
	ResponseCode sql.NullInt64
}

func (q *Queries) ListAllMonitorLogLastChecked(ctx context.Context) ([]ListAllMonitorLogLastCheckedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllMonitorLogLastChecked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMonitorLogLastCheckedRow{}
	for rows.Next() {
		var i ListAllMonitorLogLastCheckedRow
		if err := rows.Scan(&i.MonitorID, &i.CheckedAt, &i.ResponseCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailGroupIDsByMonitorID = `-- name: ListMailGroupIDsByMonitorID :many
select
    mail_group_id, slug
from
    mail_group_monitor
    left join mail_group on mail_group.id = mail_group_id
where
    monitor_id = ?
`

type ListMailGroupIDsByMonitorIDRow struct {
	MailGroupID int64
	Slug        sql.NullString
}

func (q *Queries) ListMailGroupIDsByMonitorID(ctx context.Context, monitorID int64) ([]ListMailGroupIDsByMonitorIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMailGroupIDsByMonitorID, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailGroupIDsByMonitorIDRow{}
	for rows.Next() {
		var i ListMailGroupIDsByMonitorIDRow
		if err := rows.Scan(&i.MailGroupID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailGroupMembersEmailsByMonitorID = `-- name: ListMailGroupMembersEmailsByMonitorID :many
select distinct
    email_address
from
    mail_group_member
    left join mail_group on mail_group.id = mail_group_member.mail_group_id
    left join mail_group_monitor on mail_group_monitor.mail_group_id = mail_group.id
where
    mail_group_monitor.monitor_id = ?
`

func (q *Queries) ListMailGroupMembersEmailsByMonitorID(ctx context.Context, monitorID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMailGroupMembersEmailsByMonitorID, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email_address string
		if err := rows.Scan(&email_address); err != nil {
			return nil, err
		}
		items = append(items, email_address)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
select
    id, slug, name, url, method, frequency, timeout, attempts,
    request_headers, body_format, body
from
    monitor
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Frequency,
			&i.Timeout,
			&i.Attempts,
			&i.RequestHeaders,
			&i.BodyFormat,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsByMonitorID = `-- name: ListNotificationChannelsByMonitorID :many
select
    notification_channel.id, notification_channel.slug,
    notification_channel.name, notification_channel.type,
    notification_channel.details
from
    monitor_notification_channel
    left join notification_channel
        on notification_channel.id = monitor_notification_channel.notification_channel_id
where
    monitor_notification_channel.monitor_id = ?
`

type ListNotificationChannelsByMonitorIDRow struct {
	ID      sql.NullInt64
	Slug    sql.NullString
	Name    sql.NullString
	Type    sql.NullString
	Details sql.NullString
}

func (q *Queries) ListNotificationChannelsByMonitorID(ctx context.Context, monitorID int64) ([]ListNotificationChannelsByMonitorIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannelsByMonitorID, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationChannelsByMonitorIDRow{}
	for rows.Next() {
		var i ListNotificationChannelsByMonitorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitorSlug = `-- name: UpdateMonitorSlug :one
update monitor set slug = ? where slug = ? returning id
`

type UpdateMonitorSlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) UpdateMonitorSlug(ctx context.Context, arg UpdateMonitorSlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateMonitorSlug, arg.Slug, arg.Slug_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateSeverity = `-- name: UpdateSeverity :exec
update severity set severity = ?
`

func (q *Queries) UpdateSeverity(ctx context.Context, severity string) error {
	_, err := q.db.ExecContext(ctx, updateSeverity, severity)
	return err
}
