// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addMailGroupMember = `-- name: AddMailGroupMember :exec
insert into mail_group_member(email_address, mail_group_id) values(?, ?)
on conflict (mail_group_id, email_address) do nothing
`

type AddMailGroupMemberParams struct {
	EmailAddress string
	MailGroupID  int64
}

func (q *Queries) AddMailGroupMember(ctx context.Context, arg AddMailGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addMailGroupMember, arg.EmailAddress, arg.MailGroupID)
	return err
}

const createMailGroup = `-- name: CreateMailGroup :one
insert into mail_group(slug, name, description) values(?, ?, ?) returning id
`

type CreateMailGroupParams struct {
	Slug        string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateMailGroup(ctx context.Context, arg CreateMailGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMailGroup, arg.Slug, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :exec
insert into notification_channel(slug, name, type, details) values(?, ?, ?, ?)
`

type CreateNotificationChannelParams struct {
	Slug    string
	Name    string
	Type    string
	Details string
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationChannel,
		arg.Slug,
		arg.Name,
		arg.Type,
		arg.Details,
	)
	return err
}

const deleteMailGroupByID = `-- name: DeleteMailGroupByID :exec
delete from mail_group where id = ?
`

func (q *Queries) DeleteMailGroupByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMailGroupByID, id)
	return err
}

const deleteMailGroupMembersByGroupID = `-- name: DeleteMailGroupMembersByGroupID :exec
delete from mail_group_member where mail_group_id = ?
`

func (q *Queries) DeleteMailGroupMembersByGroupID(ctx context.Context, mailGroupID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMailGroupMembersByGroupID, mailGroupID)
	return err
}

const deleteNotificationChannelByID = `-- name: DeleteNotificationChannelByID :exec
delete from notification_channel where id = ?
`

func (q *Queries) DeleteNotificationChannelByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationChannelByID, id)
	return err
}

const editNotificationChannel = `-- name: EditNotificationChannel :exec
update notification_channel set name = ?, details = ?
where id = ?
`

type EditNotificationChannelParams struct {
	Name    string
	Details string
	ID      int64
}

func (q *Queries) EditNotificationChannel(ctx context.Context, arg EditNotificationChannelParams) error {
	_, err := q.db.ExecContext(ctx, editNotificationChannel, arg.Name, arg.Details, arg.ID)
	return err
}

const getMailGroupByID = `-- name: GetMailGroupByID :one
select id, name, description from mail_group where id = ?
`

type GetMailGroupByIDRow struct {
	ID          int64
	Name        string
	Description sql.NullString
}

func (q *Queries) GetMailGroupByID(ctx context.Context, id int64) (GetMailGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMailGroupByID, id)
	var i GetMailGroupByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
select id, slug, name, type, details from notification_channel
where id = ?
`

func (q *Queries) GetNotificationChannelByID(ctx context.Context, id int64) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Details,
	)
	return i, err
}

const getNotificationChannelBySlug = `-- name: GetNotificationChannelBySlug :one
select id, slug, name, type, details from notification_channel
where slug = ?
`

func (q *Queries) GetNotificationChannelBySlug(ctx context.Context, slug string) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannelBySlug, slug)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Details,
	)
	return i, err
}

const listMailGroupMembersByID = `-- name: ListMailGroupMembersByID :many
select id, email_address from mail_group_member where mail_group_id = ?
`

type ListMailGroupMembersByIDRow struct {
	ID           int64
	EmailAddress string
}

func (q *Queries) ListMailGroupMembersByID(ctx context.Context, mailGroupID int64) ([]ListMailGroupMembersByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMailGroupMembersByID, mailGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailGroupMembersByIDRow{}
	for rows.Next() {
		var i ListMailGroupMembersByIDRow
		if err := rows.Scan(&i.ID, &i.EmailAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailGroups = `-- name: ListMailGroups :many
select id, slug, name, description from mail_group
`

func (q *Queries) ListMailGroups(ctx context.Context) ([]MailGroup, error) {
	rows, err := q.db.QueryContext(ctx, listMailGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailGroup{}
	for rows.Next() {
		var i MailGroup
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
select id, slug, name, type, details from notification_channel
where ?1 is null or type = ?1
`

func (q *Queries) ListNotificationChannels(ctx context.Context, type_ interface{}) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMailGroup = `-- name: UpdateMailGroup :exec
update mail_group set name = ?, description = ? where id = ?
`

type UpdateMailGroupParams struct {
	Name        string
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateMailGroup(ctx context.Context, arg UpdateMailGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateMailGroup, arg.Name, arg.Description, arg.ID)
	return err
}

const updateMailGroupSlug = `-- name: UpdateMailGroupSlug :one
update mail_group set slug = ? where slug = ? returning id
`

type UpdateMailGroupSlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) UpdateMailGroupSlug(ctx context.Context, arg UpdateMailGroupSlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateMailGroupSlug, arg.Slug, arg.Slug_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateNotificationChannelSlug = `-- name: UpdateNotificationChannelSlug :one
update notification_channel set slug = ? where slug = ? returning id
`

type UpdateNotificationChannelSlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) UpdateNotificationChannelSlug(ctx context.Context, arg UpdateNotificationChannelSlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationChannelSlug, arg.Slug, arg.Slug_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}
