// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlcgen

import (
	"context"
)

const createService = `-- name: CreateService :exec
insert into service(slug, name, helper_text) values(?, ?, ?)
`

type CreateServiceParams struct {
	Slug       string
	Name       string
	HelperText string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) error {
	_, err := q.db.ExecContext(ctx, createService, arg.Slug, arg.Name, arg.HelperText)
	return err
}

const deleteServiceByID = `-- name: DeleteServiceByID :exec
delete from service where id = ?
`

func (q *Queries) DeleteServiceByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteServiceByID, id)
	return err
}

const editService = `-- name: EditService :exec
update service set name = ?, helper_text = ? where id = ?
`

type EditServiceParams struct {
	Name       string
	HelperText string
	ID         int64
}

func (q *Queries) EditService(ctx context.Context, arg EditServiceParams) error {
	_, err := q.db.ExecContext(ctx, editService, arg.Name, arg.HelperText, arg.ID)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
select id, name, helper_text from service where id = ?
`

type GetServiceByIDRow struct {
	ID         int64
	Name       string
	HelperText string
}

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (GetServiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.HelperText)
	return i, err
}

const listServices = `-- name: ListServices :many
select
    id, slug, name, helper_text
from
    service
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HelperText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceSlug = `-- name: UpdateServiceSlug :one
update service set slug = ? where slug = ? returning id
`

type UpdateServiceSlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) UpdateServiceSlug(ctx context.Context, arg UpdateServiceSlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateServiceSlug, arg.Slug, arg.Slug_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}
