// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
insert into session(token, csrf_token, created_at, user_id) values(?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	CsrfToken string
	CreatedAt time.Time
	UserID    int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.UserID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
insert into user(username, password) values(?, ?) returning id
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserInvitation = `-- name: CreateUserInvitation :exec
insert into user_invitation(token, created_at) values(?, ?)
`

type CreateUserInvitationParams struct {
	Token     string
	CreatedAt time.Time
}

func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) error {
	_, err := q.db.ExecContext(ctx, createUserInvitation, arg.Token, arg.CreatedAt)
	return err
}

const deleteAllSessionsByUserID = `-- name: DeleteAllSessionsByUserID :exec
delete from session where user_id = ?
`

func (q *Queries) DeleteAllSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsByUserID, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from session where token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
delete from user where id = ?
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const deleteUserInvitation = `-- name: DeleteUserInvitation :exec
delete from user_invitation where id = ?
`

func (q *Queries) DeleteUserInvitation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserInvitation, id)
	return err
}

const editUser = `-- name: EditUser :exec
update user set username = ?, password = ? where id = ?
`

type EditUserParams struct {
	Username string
	Password string
	ID       int64
}

func (q *Queries) EditUser(ctx context.Context, arg EditUserParams) error {
	_, err := q.db.ExecContext(ctx, editUser, arg.Username, arg.Password, arg.ID)
	return err
}

const editUserUsername = `-- name: EditUserUsername :exec
update user set username = ? where id = ?
`

type EditUserUsernameParams struct {
	Username string
	ID       int64
}

func (q *Queries) EditUserUsername(ctx context.Context, arg EditUserUsernameParams) error {
	_, err := q.db.ExecContext(ctx, editUserUsername, arg.Username, arg.ID)
	return err
}

const getPasswordHash = `-- name: GetPasswordHash :one
select password, id from user where username = ?
`

type GetPasswordHashRow struct {
	Password string
	ID       int64
}

func (q *Queries) GetPasswordHash(ctx context.Context, username string) (GetPasswordHashRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHash, username)
	var i GetPasswordHashRow
	err := row.Scan(&i.Password, &i.ID)
	return i, err
}

const getUsernameByID = `-- name: GetUsernameByID :one
select username from user where id = ?
`

func (q *Queries) GetUsernameByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsernameByID, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const listActiveUserInvitations = `-- name: ListActiveUserInvitations :many
select id, token, created_at from user_invitation where created_at > ? order by id desc
`

func (q *Queries) ListActiveUserInvitations(ctx context.Context, createdAt time.Time) ([]UserInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserInvitations, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInvitation{}
	for rows.Next() {
		var i UserInvitation
		if err := rows.Scan(&i.ID, &i.Token, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select id, username from user
`

type ListUsersRow struct {
	ID       int64
	Username string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSessions = `-- name: PruneSessions :execrows
delete from session where id in (
    select id from session where session.created_at < ? limit ?
)
`

type PruneSessionsParams struct {
	CreatedAt time.Time
	Limit     int64
}

func (q *Queries) PruneSessions(ctx context.Context, arg PruneSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneSessions, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneUserInvitations = `-- name: PruneUserInvitations :execrows
delete from user_invitation where id in (
    select id from user_invitation where user_invitation.created_at < ? limit ?
)
`

type PruneUserInvitationsParams struct {
	CreatedAt time.Time
	Limit     int64
}

func (q *Queries) PruneUserInvitations(ctx context.Context, arg PruneUserInvitationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneUserInvitations, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const validateSession = `-- name: ValidateSession :one
select
    user.id, session.csrf_token
from
    user
    left join session on session.user_id = user.id
where
    session.token = ? and session.created_at > ?
`

type ValidateSessionParams struct {
	Token     string
	CreatedAt time.Time
}

type ValidateSessionRow struct {
	ID        int64
	CsrfToken sql.NullString
}

func (q *Queries) ValidateSession(ctx context.Context, arg ValidateSessionParams) (ValidateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, validateSession, arg.Token, arg.CreatedAt)
	var i ValidateSessionRow
	err := row.Scan(&i.ID, &i.CsrfToken)
	return i, err
}

const validateUserInvitationToken = `-- name: ValidateUserInvitationToken :one
select id from user_invitation where token = ? and created_at > ?
`

type ValidateUserInvitationTokenParams struct {
	Token     string
	CreatedAt time.Time
}

func (q *Queries) ValidateUserInvitationToken(ctx context.Context, arg ValidateUserInvitationTokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateUserInvitationToken, arg.Token, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
